version: '3.8'
services:
  web:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./www:/usr/share/nginx/html:ro
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    - API_ENDPOINT=api
    - API_FORWARD_DOMAIN=api:8000
  api:
    build: .
    ports:
    - "8000:8000"
  mongo:
    image: mongo
    restart: always