version: '3.8'
services:
  web:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./www:/usr/share/nginx/html:ro
    ports:
    - "80:80"
  api:
    build: .
    ports:
    - "8000:8000"
  mongo:
    image: mongo
    restart: always